services:
  server:
    build: ./server
    container_name: arp_server
    networks:
      arpnet:
        ipv4_address: 172.28.0.10

  victim:
    build: ./victim
    container_name: arp_victim
    depends_on:
      - server
    environment:
      SERVER_URL: http://172.28.0.10/
      CLIENT_ID: victim1
    networks:
      arpnet:
        ipv4_address: 172.28.0.20

  attacker:
    build: ./attacker
    container_name: arp_attacker
    depends_on:
      - server
      - victim
    cap_add:
      - NET_ADMIN
      - NET_RAW
    networks:
      arpnet:
        ipv4_address: 172.28.0.30
    environment:
      VICTIM_IP: 172.28.0.20
      SERVER_IP: 172.28.0.10
      ATTACK_INTERFACE: eth0

networks:
  arpnet:
    driver: bridge
    ipam:
      config:
        - subnet: 172.28.0.0/24
